# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "io.mattmoor.cloudevents.golang"
version = "0.0.0"
name = "CloudEvents Go Functions"
homepage = "https://github.com/mattmoor/cloudevents-go-fn"

# These orders are largely based on the equivalent from
# the Paketo buildpackage at the tag referenced in ./package.toml
[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.2.5"

  [[order.group]]
    id = "io.mattmoor.cloudevents.golang.functions"
    version = "0.0.0"
    optional = true

  [[order.group]]
    id = "io.mattmoor.http.golang.functions"
    version = "0.0.1"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/go-mod-vendor"
    version = "0.0.169"

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "0.1.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go-dist"
    version = "0.2.5"

  [[order.group]]
    id = "io.mattmoor.cloudevents.golang.functions"
    version = "0.0.0"
    optional = true

  [[order.group]]
    id = "io.mattmoor.http.golang.functions"
    version = "0.0.1"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/go-build"
    version = "0.1.2"

